pool:
  vmImage: ubuntu-latest
stages:
  - stage: ci
    displayName: Continuous Integration
    jobs:
    - job: build
      displayName: Build Project Assets
      container: mcr.microsoft.com/dotnet/sdk:6.0
      steps:
      - script: |
          dotnet publish \
          --configuration Release \
          --output out \
          --self-contained \
          --runtime win-x64 \
          -p:EnableCompressionInSingleFile=true \
          -p:PublishSingleFile=true \
          -P:PublishReadyToRun=true \
          -p:DebugType=embedded 
        displayName: Publish .NET console Project
      - publish: out/Contoso.Spaces.Console.exe
        displayName: Upload console app artifact
        artifact: console-app
      - script: |
          dotnet pack \
          --output pkg \
          -p:Version=1.0.0
        displayName: Package dotnet tool
      - publish: pkg/Contoso.Spaces.Console.1.0.0.nupk
        displayName: Upload package artifact
        artifact: nuget-package
